# Generated by Django 3.2.13 on 2022-05-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupujacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='samochod',
            name='cena',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samochod',
            name='pojemnosc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Kupno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kupujacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komis.kupujacy')),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komis.samochod')),
            ],
        ),
    ]
