# Generated by Django 3.2.13 on 2022-05-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('komis', '0002_auto_20220501_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('przebieg', models.IntegerField()),
                ('rok_produkcji', models.IntegerField()),
                ('moc', models.IntegerField()),
                ('pojemnosc', models.FloatField()),
                ('cena', models.IntegerField()),
                ('paliwo', models.CharField(choices=[('B', 'Benzyna'), ('D', 'Diesel'), ('L', 'LPG')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Kupujacy',
            new_name='Buyer',
        ),
        migrations.DeleteModel(
            name='Kupno',
        ),
        migrations.DeleteModel(
            name='Samochod',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komis.buyer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komis.car'),
        ),
    ]
