# Generated by Django 3.2.13 on 2022-05-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komis', '0003_auto_20220503_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='paliwo',
            field=models.CharField(choices=[('b', 'Benzyna'), ('d', 'Diesel'), ('l', 'LPG')], max_length=1),
        ),
    ]
