# Generated by Django 3.2.13 on 2022-05-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('komis', '0004_alter_car_paliwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Buyer',
            new_name='Kupujacy',
        ),
        migrations.RenameModel(
            old_name='Car',
            new_name='Samochod',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='kupno',
            name='kupujacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komis.kupujacy'),
        ),
        migrations.AddField(
            model_name='kupno',
            name='samochod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komis.samochod'),
        ),
    ]
