# Generated by Django 3.2.13 on 2022-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komis', '0007_alter_samochod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochod',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
