# Generated by Django 3.2.13 on 2022-05-24 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('komis', '0009_alter_samochod_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kupno',
            name='kupujacy',
        ),
        migrations.AddField(
            model_name='kupno',
            name='sprzedajacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samochod',
            name='sprzedajacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
